/**
 * ============================================================
 *  TAJONERA EVENTS SERVICES — MAIN SCRIPT
 *  ============================================================
 *  This file reads from config.js and builds the website.
 *  Do NOT edit this file unless you are a developer.
 *  All customization should be done in config.js only.
 * ============================================================
 */

(function () {
  'use strict';

  // ── SAFETY: Check config exists ──
  if (typeof CONFIG === 'undefined') {
    console.error('TES: config.js not loaded. Please ensure config.js is included before script.js.');
    return;
  }

  const C = CONFIG;

  /* ============================================================
     1. APPLY CSS VARIABLES FROM CONFIG COLORS
  ============================================================ */
  function applyTheme() {
    const root = document.documentElement;
    const colors = C.colors || {};
    if (colors.primary)    root.style.setProperty('--primary',    colors.primary);
    if (colors.secondary)  root.style.setProperty('--secondary',  colors.secondary);
    if (colors.accent)     root.style.setProperty('--accent',     colors.accent);
    if (colors.dark)       root.style.setProperty('--dark',       colors.dark);
    if (colors.darkMid)    root.style.setProperty('--dark-mid',   colors.darkMid);
    if (colors.text)       root.style.setProperty('--text',       colors.text);
    if (colors.textMuted)  root.style.setProperty('--text-muted', colors.textMuted);
    if (colors.glow)       root.style.setProperty('--glow',       colors.glow);
  }

  /* ============================================================
     2. BUILD LOGO (monogram fallback or image)
  ============================================================ */
  function buildLogo(container) {
    if (!container) return;
    if (C.logoURL && C.logoURL.trim() !== '') {
      const img = document.createElement('img');
      img.src = C.logoURL;
      img.alt = C.businessName || 'Logo';
      img.onerror = function () { this.style.display = 'none'; buildMonogram(container); };
      container.appendChild(img);
    } else {
      buildMonogram(container);
    }
  }

  function buildMonogram(container) {
    const wrap = document.createElement('div');
    wrap.className = 'logo-monogram';
    const letters = document.createElement('span');
    letters.className = 'logo-letters';
    letters.textContent = 'T E S';
    const name = document.createElement('span');
    name.className = 'logo-name';
    name.textContent = C.businessName || 'Tajonera Events Services';
    wrap.appendChild(letters);
    wrap.appendChild(name);
    container.appendChild(wrap);
  }

  /* ============================================================
     3. HERO SECTION — background detect + content
  ============================================================ */
  function buildHero() {
    // Title & tagline
    setText('heroTagline', C.tagline || '');
    setText('heroTitle', C.businessName || '');

    // Background
    const bgURL = (C.backgroundURL || '').trim();
    const bgEl = document.getElementById('heroBg');
    if (!bgEl) return;

    if (!bgURL) return; // use default CSS gradient

    const isVideo = /\.(mp4|webm|ogg)(\?.*)?$/i.test(bgURL);

    if (isVideo) {
      const video = document.createElement('video');
      video.setAttribute('autoplay', '');
      video.setAttribute('muted', '');
      video.setAttribute('loop', '');
      video.setAttribute('playsinline', '');
      video.style.cssText = 'position:absolute;inset:0;width:100%;height:100%;object-fit:cover;';
      const src = document.createElement('source');
      src.src = bgURL;
      src.type = 'video/mp4';
      video.appendChild(src);
      video.onerror = function () { this.remove(); };
      bgEl.appendChild(video);
    } else {
      bgEl.style.backgroundImage = `url('${bgURL}')`;
      bgEl.style.backgroundSize = 'cover';
      bgEl.style.backgroundPosition = 'center';
    }
  }

  /* ============================================================
     4. ABOUT SECTION
  ============================================================ */
  function buildAbout() {
    const about = C.about || {};
    setText('aboutHeading', about.heading || '');
    setText('aboutText', about.text || '');

    const statsEl = document.getElementById('aboutStats');
    if (!statsEl || !Array.isArray(about.highlights)) return;

    statsEl.classList.add('reveal-stagger');
    about.highlights.forEach(function (h) {
      const card = document.createElement('div');
      card.className = 'stat-card';
      card.innerHTML = `
        <div class="stat-icon">${escHtml(h.icon || '✦')}</div>
        <div class="stat-value">${escHtml(h.value || '')}</div>
        <div class="stat-label">${escHtml(h.label || '')}</div>
      `;
      statsEl.appendChild(card);
    });
  }

  /* ============================================================
     5. SERVICES — dynamically generated from config
     HOW TO ADD SERVICES: edit config.js → services array
  ============================================================ */
  function buildServices() {
    const grid = document.getElementById('servicesGrid');
    if (!grid) return;
    if (!Array.isArray(C.services) || C.services.length === 0) {
      grid.innerHTML = '<p style="color:var(--text-muted);text-align:center;">No services configured yet.</p>';
      return;
    }

    grid.classList.add('reveal-stagger');

    C.services.forEach(function (svc) {
      const card = document.createElement('div');
      card.className = 'service-card reveal';

      // Media block
      const media = document.createElement('div');
      media.className = 'service-media';

      const videoURL = (svc.video || '').trim();
      const imageURL = (svc.image || '').trim();

      if (videoURL) {
        const isEmbed = /youtube\.com\/embed|youtu\.be/i.test(videoURL);
        if (isEmbed) {
          const iframe = document.createElement('iframe');
          iframe.src = videoURL;
          iframe.setAttribute('allowfullscreen', '');
          iframe.setAttribute('loading', 'lazy');
          iframe.title = svc.title || 'Service video';
          iframe.onerror = function () { this.remove(); };
          media.appendChild(iframe);
        } else {
          const vid = document.createElement('video');
          vid.src = videoURL;
          vid.setAttribute('muted', '');
          vid.setAttribute('loop', '');
          vid.setAttribute('playsinline', '');
          vid.setAttribute('loading', 'lazy');
          vid.onerror = function () { this.remove(); };
          media.appendChild(vid);
        }
      } else if (imageURL) {
        const img = document.createElement('img');
        img.src = imageURL;
        img.alt = svc.title || 'Service';
        img.loading = 'lazy';
        img.onerror = function () {
          this.remove();
          const ph = document.createElement('div');
          ph.className = 'service-media-placeholder';
          ph.innerHTML = `<span>${escHtml(svc.icon || '✦')}</span>`;
          media.appendChild(ph);
        };
        media.appendChild(img);
      } else {
        const ph = document.createElement('div');
        ph.className = 'service-media-placeholder';
        ph.innerHTML = `<span>${escHtml(svc.icon || '✦')}</span>`;
        media.appendChild(ph);
      }

      // Body
      const body = document.createElement('div');
      body.className = 'service-body';
      body.innerHTML = `
        <span class="service-icon">${escHtml(svc.icon || '✦')}</span>
        <h3 class="service-title">${escHtml(svc.title || 'Service')}</h3>
        <p class="service-desc">${escHtml(svc.description || '')}</p>
      `;

      const accent = document.createElement('div');
      accent.className = 'service-card-accent';

      card.appendChild(media);
      card.appendChild(body);
      card.appendChild(accent);
      grid.appendChild(card);
    });
  }

  /* ============================================================
     6. GALLERY — dynamically generated from config
     HOW TO ADD GALLERY ITEMS: edit config.js → gallery array
  ============================================================ */
  function buildGallery() {
    const grid = document.getElementById('galleryGrid');
    if (!grid) return;
    if (!Array.isArray(C.gallery) || C.gallery.length === 0) {
      grid.innerHTML = '<p style="color:var(--text-muted);text-align:center;">No gallery items configured yet.</p>';
      return;
    }

    grid.classList.add('reveal-stagger');

    C.gallery.forEach(function (item) {
      if (!item || !item.url) return;
      const el = document.createElement('div');
      el.className = 'gallery-item reveal';

      const overlay = document.createElement('div');
      overlay.className = 'gallery-item-overlay';
      overlay.innerHTML = '<span class="gallery-zoom">⊕</span>';

      if (item.type === 'video') {
        const isYT = /youtube\.com\/embed|youtu\.be/i.test(item.url);
        if (isYT) {
          const iframe = document.createElement('iframe');
          iframe.src = item.url;
          iframe.setAttribute('allowfullscreen', '');
          iframe.setAttribute('loading', 'lazy');
          iframe.title = 'Gallery video';
          el.appendChild(iframe);
        } else {
          const vid = document.createElement('video');
          vid.src = item.url;
          vid.setAttribute('controls', '');
          vid.setAttribute('loading', 'lazy');
          vid.onerror = function () { el.remove(); };
          el.appendChild(vid);
        }
      } else {
        const img = document.createElement('img');
        img.src = item.url;
        img.alt = 'Gallery';
        img.loading = 'lazy';
        img.onerror = function () { el.remove(); };
        el.appendChild(img);
        el.appendChild(overlay);

        // Lightbox on click
        el.addEventListener('click', function () {
          openLightbox(item.url);
        });
      }

      grid.appendChild(el);
    });
  }

  /* ── Lightbox ── */
  function openLightbox(src) {
    const lb = document.getElementById('lightbox');
    const img = document.getElementById('lightboxImg');
    if (!lb || !img) return;
    img.src = src;
    lb.classList.add('active');
    document.body.style.overflow = 'hidden';
  }

  function closeLightbox() {
    const lb = document.getElementById('lightbox');
    const img = document.getElementById('lightboxImg');
    if (!lb) return;
    lb.classList.remove('active');
    if (img) img.src = '';
    document.body.style.overflow = '';
  }

  function buildLightbox() {
    const lb = document.createElement('div');
    lb.id = 'lightbox';
    lb.setAttribute('role', 'dialog');
    lb.setAttribute('aria-label', 'Image lightbox');
    lb.innerHTML = `
      <button id="lightboxClose" aria-label="Close">&times;</button>
      <img id="lightboxImg" alt="Gallery image" />
    `;
    document.body.appendChild(lb);

    const closeBtn = document.getElementById('lightboxClose');
    if (closeBtn) closeBtn.addEventListener('click', closeLightbox);
    lb.addEventListener('click', function (e) {
      if (e.target === lb) closeLightbox();
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') closeLightbox();
    });
  }

  /* ============================================================
     7. COMMITMENT SECTION
  ============================================================ */
  function buildCommitment() {
    try {
      const commitment = C.commitment || {};
      const intro = document.getElementById('commitmentIntro');
      if (intro) intro.textContent = commitment.intro || '';

      const grid = document.getElementById('commitmentGrid');
      if (!grid) return;
      if (!Array.isArray(commitment.items) || commitment.items.length === 0) return;

      grid.classList.add('reveal-stagger');

      commitment.items.forEach(function (item) {
        try {
          const card = document.createElement('div');
          card.className = 'commitment-card reveal';

          const iconWrap = document.createElement('div');
          iconWrap.className = 'commitment-icon';
          const iconEl = document.createElement('i');
          iconEl.className = item.icon || 'fas fa-check';
          iconWrap.appendChild(iconEl);

          const titleEl = document.createElement('h3');
          titleEl.className = 'commitment-title';
          titleEl.textContent = item.title || '';

          const textEl = document.createElement('p');
          textEl.className = 'commitment-text';
          textEl.textContent = item.text || '';

          const accentLine = document.createElement('div');
          accentLine.className = 'commitment-accent';

          card.appendChild(iconWrap);
          card.appendChild(titleEl);
          card.appendChild(textEl);
          card.appendChild(accentLine);
          grid.appendChild(card);

          setTimeout(function () { card.classList.add('visible'); }, 100);
        } catch (e) {
          console.warn('TES: commitment card error', e);
        }
      });
    } catch (err) {
      console.error('TES: buildCommitment failed.', err);
    }
  }

  /* ============================================================
     8. BOOKING — Google Form linked or fallback
     HOW TO LINK GOOGLE FORM: see config.js instructions
  ============================================================ */
  function buildBooking() {
      const inner = document.getElementById('bookingInner');
      if (!inner) return;

      const formLink = (C.googleFormLink || '').trim();

      const fallback = document.createElement('div');
      fallback.className = 'booking-fallback reveal';

      if (formLink) {
        fallback.innerHTML = `
          <p>Ready to make your event unforgettable? Click below to fill out our booking form.</p>
          <a href="${escHtml(formLink)}" target="_blank" rel="noopener noreferrer" class="btn btn-primary">
            Book Now
          </a>
        `;
      } else {
        const email = escHtml((C.contact && C.contact.email) || '');
        fallback.innerHTML = `
          <p>We'd love to be part of your special day. Reach out to us to get started.</p>
          <a href="mailto:${email}" class="btn btn-primary">
            Contact Us to Book
          </a>
        `;
      }

      inner.appendChild(fallback);
  }

  /* ============================================================
     8. GOOGLE SHEETS EMBED (optional)
     HOW TO EMBED GOOGLE SHEETS: see config.js instructions
  ============================================================ */
  function buildSheetEmbed() {
    const sheetURL = (C.googleSheetEmbed || '').trim();
    const section = document.getElementById('sheetSection');
    const embedEl = document.getElementById('sheetEmbed');
    if (!section || !embedEl) return;

    if (sheetURL) {
      section.style.display = '';
      const iframe = document.createElement('iframe');
      iframe.src = sheetURL;
      iframe.title = 'Booking Calendar';
      iframe.setAttribute('frameborder', '0');
      iframe.setAttribute('loading', 'lazy');
      embedEl.appendChild(iframe);
    } else {
      section.style.display = 'none';
    }
  }

  /* ============================================================
     9. CONTACT SECTION
  ============================================================ */
  function buildContact() {
    const grid = document.getElementById('contactGrid');
    if (grid) {
      const contact = C.contact || {};
      const items = [
        { icon: '☎', label: 'Phone',   value: contact.phone   || '' },
        { icon: '✉', label: 'Email',   value: contact.email   || '' },
        { icon: '⌖', label: 'Address', value: contact.address || '' },
        { icon: '◷', label: 'Hours',   value: contact.hours   || '' },
      ].filter(i => i.value);

      grid.classList.add('reveal-stagger');
      items.forEach(function (item) {
        const card = document.createElement('div');
        card.className = 'contact-card reveal';
        card.innerHTML = `
          <div class="contact-icon">${item.icon}</div>
          <div class="contact-label">${escHtml(item.label)}</div>
          <div class="contact-value">${escHtml(item.value)}</div>
        `;
        grid.appendChild(card);
      });
    }

    // Social links
    const socialEl = document.getElementById('socialLinks');
    if (socialEl && C.social) {
      const platforms = [
        { key: 'facebook',  label: 'Facebook'  },
        { key: 'instagram', label: 'Instagram' },
        { key: 'tiktok',    label: 'TikTok'    },
        { key: 'youtube',   label: 'YouTube'   },
        ];

        platforms.forEach(function (p) {
        const entry = C.social[p.key] || {};
        const url  = (entry.url  || '').trim();
        const icon = (entry.icon || '').trim();
        if (!url) return;
        const a = document.createElement('a');
        a.href = url;
        a.target = '_blank';
        a.rel = 'noopener noreferrer';
        a.className = 'social-btn';
        a.innerHTML = icon
            ? `<i class="${escHtml(icon)}"></i> <span>${escHtml(p.label)}</span>`
            : `<span>${escHtml(p.label)}</span>`;
        socialEl.appendChild(a);
        });
    }
  }

  /* ============================================================
     10. FOOTER
  ============================================================ */
  function buildFooter() {
    const footerLogo = document.getElementById('footerLogo');
    if (footerLogo) buildLogo(footerLogo);

    const copy = document.getElementById('footerCopy');
    const year = new Date().getFullYear();
    if (copy) copy.textContent = `© ${year} ${C.businessName || 'Tajonera Events Services'}. All Rights Reserved.`;

    const tag = document.getElementById('footerTagline');
    if (tag) tag.textContent = C.tagline || '';
  }

  /* ============================================================
     11. NAVBAR — sticky + scroll
  ============================================================ */
  function initNavbar() {
    const navbar = document.getElementById('navbar');
    const toggle = document.getElementById('navToggle');
    const links  = document.getElementById('navLinks');

    if (!navbar) return;

    // Scroll handler (debounced)
    let ticking = false;
    window.addEventListener('scroll', function () {
      if (!ticking) {
        requestAnimationFrame(function () {
          if (window.scrollY > 60) {
            navbar.classList.add('scrolled');
          } else {
            navbar.classList.remove('scrolled');
          }
          ticking = false;
        });
        ticking = true;
      }
    }, { passive: true });

    // Mobile toggle
    if (toggle && links) {
      toggle.addEventListener('click', function () {
        toggle.classList.toggle('open');
        links.classList.toggle('open');
      });

      // Close on link click
      links.querySelectorAll('a').forEach(function (a) {
        a.addEventListener('click', function () {
          toggle.classList.remove('open');
          links.classList.remove('open');
        });
      });
    }
  }

  /* ============================================================
     12. SCROLL REVEAL — IntersectionObserver
  ============================================================ */
  function initScrollReveal() {
    if (!('IntersectionObserver' in window)) {
      // Fallback: show everything
      document.querySelectorAll('.reveal, .reveal-stagger').forEach(function (el) {
        el.classList.add('visible');
      });
      return;
    }

    const observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add('visible');
          observer.unobserve(entry.target);
        }
      });
    }, { threshold: 0.12, rootMargin: '0px 0px -40px 0px' });

    document.querySelectorAll('.reveal, .reveal-stagger').forEach(function (el) {
      observer.observe(el);
    });
  }

  /* ============================================================
     13. DOCUMENT TITLE
  ============================================================ */
  function setDocTitle() {
    if (C.businessName) {
      document.title = C.businessName + (C.tagline ? ' — ' + C.tagline : '');
    }
  }

  /* ============================================================
     HELPERS
  ============================================================ */
  function setText(id, text) {
    const el = document.getElementById(id);
    if (el) el.textContent = text;
  }

  function escHtml(str) {
    if (!str) return '';
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  /* ============================================================
     INIT — Run all builders on DOM ready
  ============================================================ */
  function init() {
    applyTheme();
    setDocTitle();

    // Nav logos
    buildLogo(document.getElementById('navLogo'));

    buildHero();
    buildAbout();
    buildServices();
    buildGallery();
    buildLightbox();
    buildCommitment();
    buildBooking();
    buildSheetEmbed();
    buildContact();
    buildFooter();

    initNavbar();

    // Reveal after everything is built
    requestAnimationFrame(function () {
      initScrollReveal();
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
